[[redirects]]
  from = "/api-opencode/*"
  to = "https://opencode.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-openai/*"
  to = "https://api.openai.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-mistral/*"
  to = "https://api.mistral.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
